#ifndef NODE_H
#define NODE_H

#include<stdlib.h>
struct TreeNode
{
    struct TreeNode* child;//child TreeNode
    struct TreeNode* brother;//right brother TreeNode
    int linenumber;//Record line numbers for printing
    char name[30];//Record the specified name (token) of the unit
    int judge;//Judge=0 is the lexical unit, and judge=1 is the grammatical unit used for outputting judgments
    union 
    {
        char char_name[30];
        int int_number;
        float float_number;
    };//Record additional information for this unit, int float idname, int/float 'number
    //The grammar unit is generated by an empty string, and its int is recorded_ Number=0, the rest are marked as 1
};

#endif
